/************************************************************
 *
 *  Version.hpp
 *
 */

#ifndef OPENTXS_CORE_VERSION_HPP
#define OPENTXS_CORE_VERSION_HPP

#define OPENTXS_VERSION_MAJOR @VERSION_MAJOR @
#define OPENTXS_VERSION_MINOR @VERSION_MINOR @
#define OPENTXS_VERSION_BUGFIX @VERSION_BUGFIX @
#define OPENTXS_VERSION_HASH @VERSION_SHA1 @
#define OPENTXS_VERSION_STRING "@VERSION_STRING@"

#endif // OPENTXS_CORE_VERSION_HPP
