#!/bin/sh

clang_bin=clang-format

if ! command -v clang-format >/dev/null ; then
    clang_bin=clang-format-6.0
    if ! command -v clang-format-6.0 >/dev/null ; then
        echo -n "error: please install clang-format v6.0 in order to be able"
        echo    " to use this pre-commit git-hook"
        exit 1
    fi
fi

if ! (${clang_bin} --version | grep 6.0) ; then
    echo "Checking for clang-format version 6.0 ... failed"
    exit 1
fi

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

files=$(git diff --cached --name-only --diff-filter=AM $against | \
        grep -E '^(src|include/opentxs)' | grep pp$)
diffs=$(./scripts/build/clang-format-wrapper.sh "$files")
[ "$diffs" ] || exit 0
echo Found C++ code style formatting issues:
printf "%s\n" "$diffs"
exit 1
